language: node_js
node_js:
  - "4.2.1"
env:
  global:
    GH_REF: github.com/reactbits/markdown.git
    secure: "CCdnqhazdzZUJpwbRE0OZwpzwZT8JIt1xGedOIIpKFTteW9noIJuuCvMC6+b0hH4KLANx/mTk/iHSwYqHMkrwcoy8CqeYe4/QmMswJvLeWz/rvyPLefF1pnUZFSqzhGgXwHP0CVfZVvoRuwYg1x6eiyq4nkSBAE/ryQ+cqZvHPfScXO6S1Z9BbKhQ0IPoAQTtTphhhBHHEuOVQHjvErkQdiH2pzHmZyWynenzItrSUIY2YUlVmv9UM4ltthof4vR3RVu/IQO1lSZsqOP4ynjnIMFq6jMIc2ZjZJnqKDQ/wmZeaKl6GbVPraZa4VSntANcsP7lY2wJqPM38vlYMjSk+aEdqBvksnDSnUwK9ppFTPFK3OWOg4gaZu+dzgZCZI07eI2S7rjT9tGUwZGtr1dcklOvylrbx2Qyv8/J3tRYoOABj4u9oPb+STGduYOs/gxh4vrhp+KCN2Zx24BqfHkY2DIsBhULhGw8K1NWCxhlsh3O3Uyra5PLbX0OS1+KjGLWNOBweChD/EVwd9YNJagPoLrKvnLEXg58iw1gSPGnMtg39YHcWjrqnJLVJBV8oyDmhpOrX8Tzrnl6DXhjmslsx53U4OWH9F8RDk/uMIQvnPeAQasxVwKTAA4/VW8eBnXcXR9Tb4JUg8TQwUCb2cVQK/+KzxKLyQim0pSJzcZfzE="
script:
  - npm run lint
  - npm test
  - npm run deploy
